// ============================================================
// DATA PROJECT (fallback lokal)
// Nama field sama persis dengan kolom tabel `projects` di Supabase,
// jadi kode render tidak perlu berubah saat sumbernya ganti.
// ============================================================
const PROJECTS = [
  {
    filter: "web",
    image: "images/portofolio_1.1.png",
    title: "Web Profile Bootstrap",
    badge: "Web",
    short_desc: "Membuat web profile berbasis Bootstrap 5",
    modal_title: "Web Profile Bootstrap",
    modal_category: "Web",
    modal_desc: "Web profile berbasis Bootstrap 5 untuk memenuhi tugas Desain Web.",
    tech: "Bootstrap 5, HTML, CSS, JavaScript",
    images: "images/portofolio_1.1.png,images/portofolio_1.2.png,images/portofolio_1.3.png",
    coming_soon: false,
  },
  {
    filter: "design",
    image: "images/portofolio_2.1.png",
    title: "Aplikasi Kontak",
    badge: "Java",
    short_desc: "Aplikasi Kontak berbasis Java GUI.",
    modal_title: "UI Landing Concept",
    modal_category: "Design",
    modal_desc: "Aplikasi Kontak berbasis Java GUI sederhana untuk memenuhi UAP Algoritma dan Pemrograman.",
    tech: "Java",
    images: "images/portofolio_2.1.png,images/portofolio_2.2.png",
    coming_soon: false,
  },
  {
    filter: "music",
    image: "images/portofolio_3.png",
    title: "Theater Sound Designer",
    badge: "Music",
    short_desc: "Penata suara untuk kebutuhan Teater Drama Musikal.",
    modal_title: "Music Project",
    modal_category: "Music",
    modal_desc: "Penata suara untuk kebutuhan Teater Drama Musikal",
    tech: "FL Studio",
    images: "images/portofolio_3.png",
    coming_soon: false,
  },
  {
    filter: "mobile",
    image: "images/aplikasi-mobile/p3/p3.6.png",
    title: "Flutter Praktikum 1",
    badge: "Mobile",
    short_desc: "Aplikasi input form dan kalkulator Flutter.",
    modal_title: "Flutter Praktikum 1",
    modal_category: "Mobile Application",
    modal_desc: "Dokumentasi Praktikum 1 Aplikasi Mobile menggunakan Flutter, meliputi TextField, TextFormField, validasi form, dan kalkulator Kelas A.",
    tech: "Flutter, Dart",
    images: "images/aplikasi-mobile/p3/p3.6.png,images/aplikasi-mobile/p3/p3.7.png,images/aplikasi-mobile/p3/p3.8.png",
    github_url: "https://github.com/alfarisauliarahman/2411533006_AlfarisAuliaRahman_AplikasiMobile_A",
    coming_soon: false,
  },
  { filter: "java", title: "Java Project", short_desc: "Sedang dikembangkan.", coming_soon: true },
  { filter: "web", title: "Web Project", short_desc: "Sedang dikembangkan.", coming_soon: true },
  { filter: "design", title: "Design Project", short_desc: "Sedang dikembangkan.", coming_soon: true },
];
